version: "3.8"
services:
  postgres:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=server
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
